version: "3.8"

services:
  dev-quest-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-quest-service-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shared_db
      DB_USER: shared_user
      DB_PASSWORD: share
    ports:
      - "8080:8080"
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
